apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      type: nginx-daemonset-demo
  template:
    metadata:
      labels:
        type: nginx-daemonset-demo
    spec:
      containers:
        - image: nginx
          name: nginx
      nodeSelector:
        gpupresent: "true" # it's gonna running only on node gpupresent true

# make sure the node have label gpupresent true
# kubectl label node <node name> <label name>
# kubectl label kworker1.example.com gpupresent: "true"