apiVersion: batch/v1
kind: Job
metadata:
  name:  hello-turtle
spec:
  activeDeadlineSeconds: 10 # the job shouldn't run more than 10s. the pod will terminated after 10s
  template:
    metadata:
      name:  hello-turtle
    spec:
      containers:
      - name: busybox
        image: busybox
        command: [
          "sleep", "60",
          "echo" , "Job was active longer than the specified deadline "
          ] # sleep 60 seconds
      restartPolicy: Never
