apiVersion: batch/v1
kind: Job
metadata:
  name:  hello-turtle
spec:
  template:
    metadata:
      name:  hello-turtle
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "hello turtle!!!"]
      restartPolicy: Never
