{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fluent-bit.serviceAccountName" . }}
  labels:
{{ include "fluent-bit.labels" . | indent 4 }}
{{- end -}}
