apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  hello-turtle-cron
spec:
  schedule: "* * * * *" #it's gonna create a job object job resource for every single minute
  successfulJobsHistoryLimit: 0 #it's gonna cleanup the job immediatly
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hello Turtle Cron..."]
          restartPolicy: Never