apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: finance-rolebinding
  namespace: finance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-finance
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: adam
